### ISSUE TITLE
Algebraic Data Types

### ISSUE THREAD

**Issue by mollymorphic** [maximecb/zeta#11]
Let's discuss possible implementations, syntax, and semantics for Algebraic Data Types (https://en.wikipedia.org/wiki/Algebraic_data_type).

It should be possible to implement them as a language extension.

In terms of syntax, since we are skewing towards the ML family of languages for pattern matching (issue #5) - I propose we stick with that for syntax for ADTs and adopt something like:
 
```
type A = int * int
type B = { FirstName:string; LastName:string }
type C = Circle of int | Rectangle of int * int
type D = Day | Month | Year
```

We should also discuss features. In addition to value and structural matching, I'd personally like to see matching on types be well-supported. I'm sure we can come up with some other interesting/powerful features.

ADTs seem to be less common in dynamically typed languages, so I think it will be interesting to have a language that supports them well.

My main concerns at the moment are I would like to be able to construct/store ADTs efficiently. Behind the scenes we could just stick them in plain old zeta objects (which ftm I assume have similar semantics to JS objects) but that's more overhead than we technically need. I would also like to make sure we have coherent error messages etc.

Ofc some of this stuff is technically more about pattern matching, but I think there's some overlap in them, so we'll want to consider the other when implementing/designing the other.

**Comment by SBSTP** [comment]
Since the language is dynamically typed, I don't know if it'll possible to have exhaustive pattern matching where all the cases are covered. Should the first step of pattern matching always be matching the type? Once the type is known, the compiler can test "exhaustiveness".

**Comment by maximecb** [comment]
Those are also called tagged unions and variant types:
https://en.wikipedia.org/wiki/Tagged_union
https://en.wikipedia.org/wiki/Variant_type

There's a reason you don't typically find those in dynamic languages. The reason being that every value in a dynamic language is implicitly a tagged union (could be string, or object, or integer, or closure, etc). Tagged unions are a way for statically typed languages to emulate dynamic typing, and to get some safety guarantees.

I don't really think dynamic languages need this. It might sort of work if someone wants to work on a statically typed dialect of zeta, but it just doesn't really add expressiveness. The purpose would be to lock down or statically define the format of some data. Of course, if someone wants to implement this as part of an extension though, I won't oppose.

As for pattern matching, I want a pattern matching syntax that works with all zeta values. Strings, arrays, objects that are an instance of some prototype. We can't provide static guarantees in that setting, but we should probably make it so if some value doesn't match a pattern and you don't have a "catch all" clause, an exception is thrown. Zeta will strive to avoid silent failures, unlike JS.
