### ISSUE TITLE
Porting the Higgs x86 Assembler

### ISSUE THREAD

**Issue by maximecb** [maximecb/zeta#15]
I want to port the Higgs [x86 assembler](https://github.com/higgsjs/Higgs/blob/master/source/jit/x86.d) (written in D) to Zeta. The [executable code block](https://github.com/maximecb/zeta/issues/3) API will be needed in order to execute the compiled machine code, but it should already be possible to begin porting the assembler itself, which only requires being able to write data to an array of bytes.

**Comment by iankronquist** [comment]
Crazy idea. LLVM has a D front end and a [C backend](git@github.com:draperlaboratory/llvm-cbe.git). Just cross compile the file from D to C.

**Comment by maximecb** [comment]
I want to write the assembler in the Zeta language, not C. Also, what comes out of LLVM's C backend is bound to be some unmaintainable devil spawn, no?

**Comment by maximecb** [comment]
Closing because I'm going to write a static zeta compiler, which will likely use LLVM.
