### ISSUE TITLE
Pattern matching syntax

### ISSUE THREAD

**Issue by maximecb** [maximecb/zeta#5]
Zeta will feature an extensible grammar. One cool demo/use of this would be to implement a pattern matching syntax in zeta. The language isn't quite ready for this at the time of this posting, but at my current rate of progress, this should be feasible around September or October of 2015.

I imagine a syntax something like what's found [in OCaml](https://ocaml.org/learn/tutorials/data_types_and_matching.html):

```ml
let x = match e with | ... -> ... | ... -> ...
```

Feel free to suggest a syntax (with examples).

**Comment by mollymorphic** [comment]
Yes, I agree with this. A couple of things I'd like that I think make pattern matching *really* nice:

A compact syntax for matching with lambdas.

i.e. instead of:
`
let foo = fun (e)
    match e with
    | 4 -> "it's 4!"
    | _ -> "it's not 4!"
`
do something like this:

`
let foo =  fun 
    | 4 -> "it's 4"
    | _ -> "it's not 4!"
`

More than just matching based on structure/literal values. So for example, the ability to match on type, etc. I'll have to gather my thoughts more on this one in terms of all the things I'd like to see, but yea.

**Comment by maximecb** [comment]
That should be doable fairly easily by redefining parsing of the the "fun" atom.

**Comment by jbondc** [comment]
Possibly functional languages have adoption problems because of the syntax.

I'd seem to prefer something like:
```
let foo = fun(e) {
  switch(is e) {
      case 4: // "it's 4"
      default: 
           // "it's not 4!"
  }
}
```
Instead of a ```match``` operator, a ```regular switch``` statement is used but an ```is``` prefix means you are matching based on the ```type/identity``` instead of the value of ```e```:

Matching by value:
```
let foo = fun(e) {
  switch(e) {
      case 4: // value is 4
      default: 
           // value is something else
  }
}
```

Matching by type/structure:
```
let foo = fun(e) {
  switch(is e) {
      case 1... 255: // type is 1 to 255
      case SomeThing: // type is SomeThing
      default: 
           // type is something else
  }
}
```

**Comment by maximecb** [comment]
The point of match is also to do structural matching though, for instance:

```
match e with
| ( 1, _ ) -> "it's a list with 1 as the first element"
| _ -> "
```

I agree that syntax has been an issue. I think people can get used to the match keyword though, which honestly feels more intuitive than switch given that we're doing pattern matching. I also don't love the idea of reusing the curly braces, which are already used for sequencing. I would really like this language to be internally consistent, as much as possible.

My overall guiding principle, syntax wise is, if it doesn't matter, I'm going to pick the syntax that exists out there in the wild, the thing that should seem most familiar to people. For instance "fun" instead of "lambda". For something like match, I would tend to side with something ML-like, as that already exists in the wild. We also have that the imperative people are relatively unaware of match, so it won't matter much to them IMO.

**Comment by jbondc** [comment]
There's a ```switch on``` example here:
https://en.wikipedia.org/wiki/Algebraic_data_type
```
switch on (data.constructor)
  case Empty:
    return 0
```
At the top of that list, Ceylon seems to use ```switch```:
http://ceylon-lang.org/documentation/1.1/spec/html_single/#switchcaseelse

Not sure about other languages, the ```curly```ness was an example of the similarity.

**Comment by jbondc** [comment]
Like @gavinking arguments here:
http://transcripts.jboss.org/channel/irc.freenode.org/%23ceylonlang/2014/%23ceylonlang.2014-09-23.log.html#t2014-09-23T00:54:48

Need to add to my list of favorite quotes of 2015 :grinning: 

> @gavinking man why is the computing industry so broken?

**Comment by maximecb** [comment]
Well, if it makes you feel better, Zeta won't have pattern matching either, at least the core language won't, it will be an optional extension ;)

**Comment by jbondc** [comment]
Ya love what you're trying to do with extensions. To add more thoughts on ```switch/match```:
```
type Things = (number,number) | 1...10 | {};
let foo = fun(e)
  switch is(e) // forces exhaustive check on type matching
      case (1, any) :
      case 1...10   :
      case {}       :  
      default: 
           // "it's something else"

let foo = fun(e: Things)
  switch(e) // type matching or value matching
      case is (1, any):
      case 1: 
           // match by value 1
      default: 
           // it's 2...10 or {}
```
Not real picky about syntax but conceptually ~ those would be my preference.

**Comment by maximecb** [comment]
We'll reopen this issue once we're ready to implement language extensions.
