### ISSUE TITLE
Deciding on assignment syntax

### ISSUE THREAD

**Issue by maximecb** [maximecb/zeta#7]
This is kind of a silly issue... But we have to pick a syntax for assignments in zeta. Feel free to contribute your opinion.

Often, programming newbies are confused by the use of the "=" operator for assignments, because it's not a mathematical equality. There's some argument that we maybe should use a pascal style "x := y". We could also use "x <- y". The argument in favor of using plain old "=" is that most programmers are already familiar with Python, JS, Java, etc. It's the most common syntax.

**Comment by bFraley** [comment]
Silly, but certainly a huge decision. You could get creative with it, which could turn out well, but my opinion is to play it safe with the good old `=`

**Comment by maximecb** [comment]
I was thinking the same thing. The good old equal sign is almost a convention now.
